### ISSUE TITLE
Define versioning scheme

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.objectstorage#10]
How is versioning being used for this toolkit?

It seems to be "rushing" into 1.x releases with an api that is changing, e.g. #8 . A typical approach is to use 0.x for initial releases where api is evolving, with 1.0 being the first stable point.
 
Is it expected that the first stable release will be 2.0?

@chanskw

**Comment by chanskw** [comment]
@ddebrunner you are right.  We typically use v0.x when the toolkit and its APIs are evolving.  Once v1.0 is established, we should try our best to maintain API compatibility.

**Comment by chanskw** [comment]
Also, if things are still changing, I recommend marking the release as a pre-release.  Then people know that it is not stable yet and have expectation that API may break in the future.

**Comment by markheger** [comment]
0.3.0 (May 2, 2017)
1.0.0 should have been set to 0.4.0 (May 4, 2017)
1.1.0 should have been set to 0.5.0 (May 12, 2017
--> correct the toolkit version to 0.5.0 and tag as pre-release
