### ISSUE TITLE
Streams not flushed for timePerObject if tuples not flowing

### ISSUE THREAD

**Issue by jms90h5** [IBMStreams/streamsx.objectstorage#101]
When the timePerTuples parameter is set tuples that arrive during the current period are not flushed at the time the period ends.  The operator appears to be waiting until the next tuple arrives that is outside the specified time period to flush the tuples and close the file.  For slow streams where there can be extended periods with no tuple flow that means the application needs to use some other mechanism, such as closeOnPunct.  In that situation, if we have to do our own period/object-closure triggering it defeats the benefit of the timePerObject feature.

**Comment by joemirizio** [comment]
@markheger I'm not seeing the active object getting closed after `timePerObject` seconds. It isn't until the operator receives another message outside of the window that it gets closed. I am using version `2.2.6`.

Looking at the trace logs, I can see `ScheduledExecutorService - trigger object expiry in cache` printing every 3 seconds. The `nActiveObjects` stays at `1`, and the `nClosedObjects` is not increased.
