### ISSUE TITLE
streamsx.objectstorage: Return operators from write methods.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.objectstorage#146]
Python package write methods should return the invocation of the operator (as a Placeable) so that applications can colocate functionality, set tags etc.

**Comment by markheger** [comment]
v0.2.0 has been released 
https://pypi.org/project/streamsx.objectstorage/

**Comment by ddebrunner** [comment]
@markheger documentation doesn't indicate that any value is returned.
