### ISSUE TITLE
Clarify ObjectStorageScan behaviour

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.objectstorage#147]
The SPLDOC states the operator scans new and modified files but in fact when it starts it will produce all files in the directory. The scan behaviour should be clearly documented.

`directory` parameter is described as always optional but in fact it is required when there is no input port. I'd thought maybe it defaulted to the root directory.

**Comment by markheger** [comment]
Parameters `directory` and `pattern` should get defaults, to become optional.

**Comment by markheger** [comment]
Will be released with v1.8.0
