### ISSUE TITLE
Python: timePerObject should be flexible in what it accepts.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.objectstorage#153]
I called `write_parquet` with `timePerObject=30` and it failed at SPL compilation time.

For a `float64` the Python code should be doing:

` _op.params['timePerObject'] = float(timePerObject)`

or

 `_op.params['timePerObject'] = streamsx.spl.types.float64(timePerObject)`

**Comment by ddebrunner** [comment]
`write` also has the same issue, other parameters should also be checked to see if that can be flexible in their type.

Note for a time period supporting `datetime.timedelta` is also very useful for clearer code:

`timePerObject=datetime.timedelta(minutes=7)`

**Comment by markheger** [comment]
streamsx.objectstorage 0.4.0
