### ISSUE TITLE
Python: Follow Python PEP8 for function parameters.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.objectstorage#154]
Python PEP8 style guide recommends words spearated by underscores, not mixedCase.   `streamsx` and `streamsx.messagehub` follows this style.

The naming of the SPL parameters doesn't matter, as the assumption is the developer is a Python developer who has no knowledge of SPL.

https://www.python.org/dev/peps/pep-0008/#function-and-variable-names

E.g. `write` has `timePerObject` and `objectName`.

**Comment by markheger** [comment]
streamsx.objectstorage 0.4.0
