### ISSUE TITLE
Define default credentials clarification.

### ISSUE THREAD

**Issue by siegenth** [IBMStreams/streamsx.objectstorage#158]
On these pages: [link1](https://streamsxobjectstorage.readthedocs.io/en/pypackage/), [link2](https://github.com/IBMStreams/streamsx.objectstorage/blob/master/demo/data.historian.event.streams.cos.exactly.once.semantics.demo/dh_generate_json/README.md) you're describing how to setup credentials. I had a hard time making sure I put the values into the correct fields - here is a possible rewording...

The default configuration is "cos" with a name of "cos.creds", this can be set:
- Using the "Application Configuration" tab of the "Streams Console" 
- using page selected by the sub tab "Application Configuration"
- create a "New application configuration...'"using the "Name" "cos", no description is necessary
- set the parameter "Name" to "cos.creds" and it's "Value" to your COS "Service credentials" generated here  https://ibmstreams.github.io/streamsx.objectstorage/docs/user/objectstorageservice

Rather confusing that the tab is "Application Configuration" and the 'sub tab' is "Application Configuration"

**Comment by markheger** [comment]
SPLDOC describes it very well. Have you had a look at this?
https://ibmstreams.github.io/streamsx.objectstorage/doc/spldoc/html/tk$com.ibm.streamsx.objectstorage/op$com.ibm.streamsx.objectstorage$ObjectStorageScan$4.html

**Comment by markheger** [comment]
I would update the description in the python package with the next python package release
https://streamsxobjectstorage.readthedocs.io/en/pypackage/

**Comment by siegenth** [comment]
yes, I agree the SPLDOC  is superior 
thanks
