### ISSUE TITLE
2 sets of samples with identical names?

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.objectstorage#168]
I try to import the samples into Streams Studio and I get 2 sets of samples with the same name.
This is confusing, but the other problem is  when I imported both with the same name, I only ended up with one project in the workspace.
![Screen Shot 2019-07-11 at 7 25 58 PM](https://user-images.githubusercontent.com/1179133/61091864-cbaca780-a411-11e9-9b99-618df3bfa825.png)

**Comment by markheger** [comment]
Problem is StreamsStudio / Eclipse, that namespaces are not part of the name. Names in .project and info.xml have the long name with namespace.

**Comment by markheger** [comment]
* renaming the directory solves the problem
* iam samples will get IAM at end of directory name
