### ISSUE TITLE
Object scan sample creates too many objects

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.objectstorage#169]
If you run the sample manually and thenyou have to clean up the bucket on COS, it creates 100s of files. This is very annoying to clean up because from the COS dashboard, you cannot delete the bucket until it is empty and you can  only delete them 50 at a time.
10 files instead of 1000 would be enough to demonstrate the function.

**Comment by markheger** [comment]
There are many other ways to work with buckets, the COS dashboard is not good for many objects per bucket.
Use the python scripts provided by this repo for clean-up, for example:
https://github.com/IBMStreams/streamsx.objectstorage/blob/master/utils/README.md

**Comment by natashadsilva** [comment]
Using a script would help, thank you. But my point is it is not a very user-friendly sample. Is it not more reasonable to simplify the sample that to expect our users to know and find this script or to write their own?

**Comment by markheger** [comment]
sample shall be updated: slow down beacon rate and increase object size
