### ISSUE TITLE
Requesting a feature for S3ObjectStorageSource

### ISSUE THREAD

**Issue by iopuckoi** [IBMStreams/streamsx.objectstorage#176]
I'm using this toolkit to scan a Minio bucket (with S3ObjectStorageScan), read file changes using S3ObjectStorageSource, and pass along results to a follow-on custom operator.  However, I would like S3ObjectStorageSource to be able to pass along more than just the file's contents.  For example, in my use case, I need both the name of the file being read and the contents of the file.  I tried outputting a tuple with two rstring attributes, but the operator doesn't allow for this.

**Comment by markheger** [comment]
Currently not supported to have more than one attribute on output stream.

```
	@ContextCheck(compile = true)
	public static void checkOutputPortSchema(OperatorContextChecker checker)
			throws Exception {
		StreamSchema outputSchema = checker.getOperatorContext()
				.getStreamingOutputs().get(0).getStreamSchema();

		// check that number of attributes is 1
		if (outputSchema.getAttributeCount() != 1) {
			checker.setInvalidContext(
					Messages.getString("OBJECTSTORAGE_SOURCE_INVALID_OUTPUT"), 
					null);
		}
```

The `checkOutputPortSchema` method should be changed and the attributes from the input tuple should be forwarded to output tuple like below:


		// Copy across all matching attributes.
		outTuple.assign(inputTuple);

**Comment by bmwilli** [comment]
I could use this feature as well.  Thanks, Brian
