### ISSUE TITLE
Empty object does not result in a tuple being produced

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/streamsx.objectstorage#180]
We are using the S3ObjectSource and we have a few objects (files) that were put in S3, with empty bodies.....S3ObjectSource is not sending a tuple with the empty blob out.  

I would request a change or option such that if
* Object does not exist, dont send a tuple
* If Object exists send a tuple, even if the content of the object was empty.

P.S. This is reading in BLOB mode.

Thoughts?

Thanks,
Brian

**Comment by markheger** [comment]
ObjectStorageSource operator behaves like the FileSource, empty file (empty object) results in window marker only (no data tuple is sent on port 0).
