### ISSUE TITLE
cffi version mismatch under IBM Cloud Pak for Data

### ISSUE THREAD

**Issue by yamapa2** [IBMStreams/streamsx.objectstorage#232]
We are trying to use streams.objectstorage under IBM Cloud Pak for Data 3.5.0, import fails with a version mismatch error on cffi -

Exception: Version mismatch: this is the 'cffi' package version 1.12.2, located in '/user-home/_global_/python-3/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.14.0, located in '/home/wsuser/.local/lib/python3.7/site-packages/_cffi_backend.cpython-37m-x86_64-linux-gnu.so'.  The two versions should be equal; check your installation.

**Comment by anouri** [comment]
Closed
