### ISSUE TITLE
Issues with COS (S3) Samples 

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.objectstorage#29]
I tried to run the sample for S3 and I ran into the following issues:
1. [Project page](https://ibmstreams.github.io/streamsx.objectstorage) does not have documentation for this sample, only the swift sample
1. `Readme.md` for the sample does not mention where to get your credentials.

More importantly, I couldn't match the name of the credentials required by the sample to what was listed in the Credentials page of my cloud instance. This might be because of the new authentication mechanism.
The required parameters for the sample are 
`ObjectStorage-AccessKeyID"`, `ObjectStorage-SecretAccessKey` and `ObjectStorage-Endpoint`.
But these parameters do not exist in the JSON Credentials object for my instance:

```
{
  "apikey": "jqN2-k7u",
  "endpoints": "https://cos-service.bluemix.net/endpoints",
  "iam_apikey_description": "nnnn",
  "iam_apikey_name": "adsfdsf72e5f9d062",
  "iam_role_crn": "dfsf",
  "iam_serviceid_crn": "dffd90c5f566",
  "resource_instance_id": "fdfdfd:"
}
```

I tried matching the `apikey` and `iam_apikey_name` and `endpoints` parameters respectively but it didn't work.

**Comment by alexpy11** [comment]
@natashadsilva documentation and samples are still work in progress.
The following picture explains mapping of object storage service credentials on an object storage operator credentials. 
![operatorcredentials](https://user-images.githubusercontent.com/15964871/35500948-fb84711c-04e0-11e8-99a1-da0182f2037c.jpg)

**Comment by markheger** [comment]
IAM support for authentication will be available in an upcoming toolkit version. It is currently on iss#9-stocator-based-impl branch.

**Comment by natashadsilva** [comment]
Thanks. So the master branch currently does not support it? 
The samples refere to `ObjectStorage-AccessKeyID", ObjectStorage-SecretAccessKey and ObjectStorage-Endpoint`.  There is no AccesskeyId or AccessKey in the credentials. I checked the samples in the 9-stocator-based-impl branch and they are the same names. Accesskey and AccessKeyid are not in the IAM credentials. Will the samples be updated to match the names in the credentials map?

**Comment by markheger** [comment]
Yes, the master branch does not support it, because the toolkit has been developed and released long time before IBM COS introduced IAM.
Samples are still valid for S3 object storages, where the user has the accesskey and secretaccesskey.
There is a new sample for IAM credentials available.
IBM COS S3 supports both authentication methods, but it seems that not every user has the chance to get the accesskey and secretaccesskey credentials. It depends when and how the IBM COS S3 service has been created.

**Comment by alexpy11** [comment]
@natashadsilva the following sample on iss#9-stocator-based-impl branch provides Scan, Source and Sink examples with IAM-based authentication.
