### ISSUE TITLE
Scan/watch operator

### ISSUE THREAD

**Issue by brandtol** [IBMStreams/streamsx.objectstorage#3]
The toolkit shall contain an operator that can detect changes in the Bluemix Object Storage service.
Either by receiving notifications, and/or by reading metadata on accounts/containers/buckets etc.

Things we should consider/specify
- Supported interface : Swift and/or S3 
- Credential handling/token refresh (is Streams application config an option ?)
- Error handling
- Scan intervals/sorting , if applicable

The DirectorySan operator for reference:
https://www.ibm.com/support/knowledgecenter/SSCRJU_4.2.0/com.ibm.streams.toolkits.doc/spldoc/dita/tk$spl/op$spl.adapter$DirectoryScan.html

A filesystem notification based dir watcher operator for reference: 
https://www.ibm.com/support/knowledgecenter/SSCRJU_4.2.0/com.ibm.streams.toolkits.doc/spldoc/dita/tk$com.ibm.streams.teda/op$com.ibm.streams.teda.adapter$DirectoryWatch.html

**Comment by markheger** [comment]
releases with 1.0.0.4
