### ISSUE TITLE
Consistent Region Support

### ISSUE THREAD

**Issue by apyasic** [IBMStreams/streamsx.objectstorage#32]
Add consistent region support to the toolkit operators

**Comment by ddebrunner** [comment]
Please ensure that any operators do not just catch exceptions, trace them, and continue on.

An error means the region needs to reset if we want to guarantee at least once processing.

There seems to be one example here:
https://github.com/IBMStreams/streamsx.objectstorage/blob/iss%239-stocator-based-impl/com.ibm.streamsx.objectstorage/impl/java/src/com/ibm/streamsx/objectstorage/BaseObjectStorageSink.java#L1239
