### ISSUE TITLE
Exactly once semantics support

### ISSUE THREAD

**Issue by apyasic** [IBMStreams/streamsx.objectstorage#33]
Add only once capabilities support to the toolkit operators

**Comment by ddebrunner** [comment]
What is "only once"? Exactly once sematics?

**Comment by markheger** [comment]
On top of at least once capabilities there are use cases that need to store an object on COS exactly once.

**Comment by markheger** [comment]
- delete objects in error cases in reset()

**Comment by markheger** [comment]
add new metric `nDeletedObjects` to count number of objects deleted on reset after they are uploaded and closed. 
available in consistent region only
