### ISSUE TITLE
Update iopages for 1.x release

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.objectstorage#41]
* remove old description from pre-release
* add decription for the 1.x release

**Comment by apyasic** [comment]
Documentation extension work plan:
 - Domain knowledge
   - toolkit techical background overview
 - User documentation  
      - toolkit usage overview
      - update error handling page with up-to-date error codes
      - Operators description
           - ObjectStorageScan
           - ObjectStorageSource
           - ObjectStorageSink
 - Developer Documentation
    - Toolkit architecture overview
    - Toolkit testing

**Comment by apyasic** [comment]
In addition, proposed the following developer works:
  - Introducing the Object Storage Toolkit
  - Improving IBM Streams application throughput/performance when writing to Object Storage

**Comment by apyasic** [comment]
@markheger the documentation is completed from my side.
