### ISSUE TITLE
Window and final punctuation must not bypass data tuples

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.objectstorage#47]
ObjectStorageSink
currently final marker closes output stream before output tuple could be sent

**Comment by markheger** [comment]
Final marker needs to be hold until all threads have uploaded the object and submitted the output tuple.

**Comment by apyasic** [comment]
The following logic is implemented:
 - using `OSRegistry.closeAllImmediatly`  method for FINAL and WINDOW marker with output port. The method is blocking method. It waits for all active objects to be uploaded and committed to COS. The only case when `OSRegistry.closeAll` async method used is for WINDOW marker with no output port as it doesn't require object metadata to be extracted from COS.

**Comment by markheger** [comment]
`OSRegistry.closeAllImmediatly` can not be used for window/final marker if output port is present since it does not trigger `remove(cacheKey)`
Hence the output tuple is not sent.

**Comment by apyasic** [comment]
Good point Mark.  Please see an update on the previous comment.

**Comment by apyasic** [comment]
The latest improvement follows the following logic to avoid listener register/unregister per tuple submission: 
 - when `ObjectStorageSink` has output port the closing logic is always synchronous,  the object closed from the operator thread with no listener involvement.
 - when `ObjectStorageSink` has no output port the closing logic is always async, i.e. the entry corresponding to the object simply removed from cache (EHCache). As a result 'REMOVED` notification has been triggered and asynchronously processed by the relevant listener subscribed on `REMOVED` event.
