### ISSUE TITLE
Enhancement request to add IGC support to ObjectStorage operators

### ISSUE THREAD

**Issue by jms90h5** [IBMStreams/streamsx.objectstorage#51]
Add IGC support to the ObjectStorage operators to allow their use in applications requiring data lineage and flow metadata to be reported when an application using these assets is submitted. This capability is currently supported by other sink operators such as File, Kafka, JMS, MQTT, ...

Background Streams/IGC related information:

https://www.slideshare.net/lisanl/data-governance-with-ibm-streams-v41
http://ibmstreams.github.io/streamsx.documentation/docs/4.1/governance/governance-quickstart/
https://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.1.0/com.ibm.streams.studio.doc/doc/tworking-with-governance-catalogs.html

**Comment by markheger** [comment]
In current release ObjectStorageSink and ObjectStorageSource register already for data governance if object name is in static mode.
