### ISSUE TITLE
Fix error handling in operators.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.objectstorage#6]
The sink operator catches exceptions, logs them and then just continues on.

https://github.com/IBMStreams/streamsx.objectstorage/blob/master/com.ibm.streamsx.objectstorage/impl/java/src/com/ibm/streamsx/objectstorage/s3/ObjectSink.java#L153

This is not good practice, errors go unnoticed, no indication from the operator that something is wrong.

Typically the exception should be thrown and let the runtime log it, or maybe have retry logic in there, or an error port.

Applications can catch exceptions using the @catch annotation.

**Comment by markheger** [comment]
Changes:
- do not catch AmazonClientException
- new optional errorCodeAttribute parameter specifies the attribute that contains the error codes from AmazonServiceException

released in 1.1.0
