### ISSUE TITLE
Improve documentation for ObjectStorageSink

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.objectstorage#70]
Reading the SPLDOC for `ObjectStorageSink` I have no real idea what it is doing.

- The overview is terse.
- The input port states there are two formats supported with fixed schemas, but there is also parameters for parquet (though no real indication of how they are used) and a `dataAttribute` parameter which contradicts the fixed schema.
- There's one mention of partitions, but I don't know what partitioning scheme it is referring to.

Looks like the SPLDOC is not keeping up with the functionality.

**Comment by markheger** [comment]
Add Examples section in operator description for SPLDOC
