### ISSUE TITLE
Input attributes parameters should be attributes, not names of the attributes.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.objectstorage#8]
ObjectSource's `objectDataAttribute` and `objectNameAttribute` should be of type attribute, not rstrings.

Though `objectDataAttribute` might be for the output port, but its description says input. It's hard to tell as the SPLDOC doesn't fully describe what the operator does.

Same for ObjectSink, though I think in that case both are input attributes.

See https://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.0.0/com.ibm.streams.spl-java-operators.doc/api/com/ibm/streams/operator/TupleAttribute.html

**Comment by markheger** [comment]
Changes:
- description updated
- TupleAttribute<Tuple,String> used for parameters referencing input stream attributes

released in 1.1.0

**Comment by ddebrunner** [comment]
Any chance the toolkit could use the standard development model of pull requests?

Harder to track changes with direct commits to master.

**Comment by markheger** [comment]
Yes, for upcoming commits pull request are used.
